
[config]
project_id = "qolgehnzmslkmotrrwwy"

[[functions]]
name = "gmail-auth"
verify_jwt = false

[[functions]]
name = "send-email"
verify_jwt = false

[[functions]]
name = "refresh-token"
verify_jwt = false
